name: Profile QA - changed files
on: [pull_request]

jobs:
  nictiz-r4-qa-changed:
    name: Strict QA on changed materials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

